---
httpd_owner: "apache"
httpd_group: "apache"
httpd_port: 80
httpd_domain: "site.pratheesh.tech"
httpd_docroot: "/var/www/html/"
mariadb_root_password: "mysqlroot123"
mariadb_extra_user: "bloguser"
mariadb_extra_user_password: "bloguser123"
mariadb_extra_database: "blogdatabase"
wp_url: "https://wordpress.org/wordpress-6.0.3.tar.gz"
